# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       davfs2

# >> macros
# << macros
%define dav_group mount
%define dav_user mount
%define dav_cachedir /home/.system/var/cache/%{name}

Summary:    Linux FUSE driver that allows you to mount a WebDAV resource
Version:    1.7.0
Release:    0
Group:      System
License:    GPLv3+
URL:        https://savannah.nongnu.org/projects/davfs2/
Source0:    https://download.savannah.nongnu.org/releases/davfs2/%{name}-%{version}.tar.gz
Source1:    davfs2-rpmlintrc
Source100:  davfs2.yaml
Patch0:     Makefile.am.patch
Patch1:     filelocations.patch
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libcrypto)
BuildRequires:  pkgconfig(libproxy-1.0)
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(neon)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  gettext

%description
davfs2 is a Linux file system driver that allows you to mount a WebDAV
resource into your Unix file system tree. So - and that is what makes
davfs2 different - applications can use it without knowing about WebDAV.
You may edit WebDAV resources using standard applications that interact
with the file system as usual.

davfs2 supports SSL and proxy, HTTP authentication (basic and digest)
and client certificates.

%if 0%{?_chum}
Title: davfs2
Type: console-application
DeveloperName: Ali Abdallah
PackagedBy: nephros
Categories:
  - Network
  - Filesystem
Custom:
  Repo: https://git.savannah.nongnu.org/git/davfs2.git
  PackagingRepo: https://github.com/sailfishos-chum/davfs2
Links:
  Homepage: %{url}
  Help: https://forum.sailfishos.org/search?q=davfs%20order%3Alikes
  Bugtracker: https://savannah.nongnu.org/bugs/?group=davfs2&func=browse&set=open
%endif


%prep
%setup -q -n %{name}-%{version}/upstream/

# Makefile.am.patch
%patch0 -p1
# filelocations.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# set the user/group in the system config file. note that this needs the patch above
sed -i "s#@@rpm_dav_user@@#%{dav_user}#"  etc/davfs2.conf
sed -i "s#@@rpm_dav_group@@#%{dav_group}#"  etc/davfs2.conf
sed -i "s#@@rpm_dav_cachedir@@#%{dav_cachedir}#"  etc/davfs2.conf
# commands from ./bootstrap, but without the gettext and gnulib stuff
autopoint --force
aclocal -I config
autoheader
automake --add-missing --force-missing --copy
autoconf
cp -p config/COPYING.davfs2 COPYING
cp -p config/INSTALL.davfs2 INSTALL
# << build pre

%configure --disable-static \
    --enable-largefile \
    --disable-nls \
    dav_group=%{dav_group} \
    dav_user=%{dav_user} \
    dav_syscachedir=%{dav_cachedir}


# >> build post
%make_build
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
install -d -m 755 %{buildroot}%{dav_cachedir}
# we don't  need the docs
rm -rf %{buildroot}%{_mandir}
rm -rf %{buildroot}%{_docdir}/%{name}
# << install post

%files
%defattr(-,root,root,-)
%{_sbindir}/*
%config(noreplace) %{_sysconfdir}/%{name}/%{name}.conf
%config(noreplace) %{_sysconfdir}/%{name}/secrets
%dir %{_sysconfdir}/%{name}/certs
%{_datadir}/%{name}
%{dav_cachedir}
# >> files
# << files
